name: DMAKE-basic-check

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - run: ./configure
    - run: make
    - run: make check
    - run: make distclean
